In [1]:
import torch

In [8]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
a = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [10]:
a = torch.tensor([[1,2,3],[4,5,6]], device="cuda")
a

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [11]:
a = torch.tensor([[1,2,3],[4,5,6]], 
                dtype=torch.float32,requires_grad=True)
a

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [14]:
device = "cuda" if torch.cuda.is_available() else "cpu"

a = torch.tensor([[1,2,3],[4,5,6]], 
                dtype=torch.float32,
                requires_grad=True,
                device=device)
print(a)
print(a.dtype)
print(a.device)
print(a.shape)
print(a.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [18]:
a = torch.empty(size=(3,3))
print(a)

a = torch.zeros(size=(3,3))
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [20]:
a = torch.rand(size=(3,3))
print(a)

tensor([[0.6009, 0.1086, 0.7567],
        [0.9815, 0.3147, 0.6987],
        [0.3903, 0.6449, 0.5923]])


In [22]:
a = torch.ones(size=(3,3))
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [25]:
a = torch.eye(5)
print(a)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [26]:
a = torch.arange(start=0, end=5, step=1)
print(a)

tensor([0, 1, 2, 3, 4])


In [27]:
a = torch.linspace(start=0.1, end=1, steps=10)
print(a)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [28]:
a = torch.empty(size=(1,5)).normal_(mean=0,std=1)
print(a)

tensor([[ 0.8503,  0.9721, -0.7903, -0.2689, -0.8571]])


In [32]:
a = torch.empty(size=(1,5)).uniform_(0,10)
print(a)

tensor([[0.3096, 2.4084, 9.7625, 5.3740, 3.4717]])


In [35]:
a = torch.diag(torch.ones(3))
print(a)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [41]:
t = torch.arange(5)
print(t)
print(t.bool())
print(t.short())
print(t.long())
print(t.half())
print(t.float())
print(t.double())

tensor([0, 1, 2, 3, 4])
tensor([False,  True,  True,  True,  True])
tensor([0, 1, 2, 3, 4], dtype=torch.int16)
tensor([0, 1, 2, 3, 4])
tensor([0., 1., 2., 3., 4.], dtype=torch.float16)
tensor([0., 1., 2., 3., 4.])
tensor([0., 1., 2., 3., 4.], dtype=torch.float64)


In [42]:
import numpy as np

In [44]:
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
print(tensor)
print(tensor.numpy())

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [45]:
a = torch.tensor([1,2,3])
b = torch.tensor([9,8,7])

In [46]:
c = torch.empty(3)
torch.add(a,b,out=c)
print(c)

tensor([10., 10., 10.])


In [47]:
c = torch.add(a,b)
print(c)
c = a+b
print(c)

tensor([10, 10, 10])
tensor([10, 10, 10])


In [48]:
c = a-b
print(c)

tensor([-8, -6, -4])


In [50]:
c = torch.true_divide(a,b)
print(c)

tensor([0.1111, 0.2500, 0.4286])


In [51]:
t = torch.zeros(3)
t.add_(a)
print(a)
print(t)

tensor([1, 2, 3])
tensor([1., 2., 3.])


In [52]:
t += a
print(t)

tensor([2., 4., 6.])


In [53]:
c = a.pow(2)
print(c)

tensor([1, 4, 9])


In [54]:
print(a**2)

tensor([1, 4, 9])


In [55]:
z = a>0
print(z)

tensor([True, True, True])


In [59]:
x1 = torch.rand(2,5)
x2 = torch.rand(5,3)
y = torch.mm(x1,x2)
print(y)
y = x1.mm(x2)
print(y)

tensor([[1.4419, 1.2242, 1.6706],
        [1.3128, 1.2973, 1.4851]])
tensor([[1.4419, 1.2242, 1.6706],
        [1.3128, 1.2973, 1.4851]])


In [60]:
# matrix exponentiation
me = torch.rand(5,5)
print(me)
print(me.matrix_power(3))

tensor([[0.4735, 0.2367, 0.9274, 0.7282, 0.6384],
        [0.4572, 0.2614, 0.9109, 0.4561, 0.1360],
        [0.1521, 0.0492, 0.1979, 0.3306, 0.4728],
        [0.1046, 0.0362, 0.6037, 0.4125, 0.6059],
        [0.2622, 0.3902, 0.0582, 0.1063, 0.5059]])
tensor([[1.2867, 1.0043, 2.1461, 1.8111, 2.6076],
        [0.9576, 0.7285, 1.6464, 1.4227, 2.0653],
        [0.5267, 0.4184, 0.8540, 0.6986, 0.9849],
        [0.6903, 0.5694, 1.0976, 0.8966, 1.3063],
        [0.6906, 0.4779, 1.2229, 0.9927, 1.2551]])


In [61]:
# element-wise multiplication

c = a*b
print(c)

tensor([ 9, 16, 21])


In [62]:
# dot product
c = torch.dot(a,b)
print(c)

tensor(46)


In [64]:
batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand(batch, n, m)
t2 = torch.rand(batch, m, p)
out_bmm = torch.bmm(t1, t2)

In [66]:
# Broad casting

x1 = torch.rand(5,5)
x2 = torch.rand(1,5)
y = x1-x2
print(x1)
print(x2)
print(y)

tensor([[0.7250, 0.8515, 0.5599, 0.4745, 0.2303],
        [0.5008, 0.1775, 0.1320, 0.0891, 0.4904],
        [0.4066, 0.2552, 0.1807, 0.2008, 0.8385],
        [0.5808, 0.0181, 0.3522, 0.7030, 0.4208],
        [0.5838, 0.7576, 0.1649, 0.6072, 0.6027]])
tensor([[0.8774, 0.4013, 0.8944, 0.7385, 0.9609]])
tensor([[-0.1524,  0.4501, -0.3345, -0.2640, -0.7306],
        [-0.3765, -0.2238, -0.7624, -0.6495, -0.4705],
        [-0.4707, -0.1461, -0.7136, -0.5377, -0.1224],
        [-0.2965, -0.3833, -0.5422, -0.0355, -0.5402],
        [-0.2935,  0.3562, -0.7295, -0.1314, -0.3583]])


In [67]:
y = x1 ** x2
print(y)

tensor([[0.7541, 0.9375, 0.5952, 0.5766, 0.2439],
        [0.5451, 0.4997, 0.1635, 0.1676, 0.5042],
        [0.4541, 0.5781, 0.2165, 0.3056, 0.8443],
        [0.6209, 0.1997, 0.3932, 0.7709, 0.4352],
        [0.6237, 0.8946, 0.1995, 0.6918, 0.6147]])


In [69]:
sum_a = torch.sum(a, dim=0)
print(sum_a)

tensor(6)


In [70]:
values, indices = torch.max(a, dim=0)
print(values, indices)

tensor(3) tensor(2)


In [71]:
values, indices = torch.min(a, dim=0)
print(values, indices)

tensor(1) tensor(0)


In [72]:
abs_a = torch.abs(a)
print(abs_a)

tensor([1, 2, 3])


In [73]:
c = torch.argmax(a, dim=0)
print(c)

tensor(2)


In [75]:
mean_a = torch.mean(a.half(), dim=0)
print(mean_a)

tensor(2., dtype=torch.float16)


In [76]:
c = torch.eq(a,b)
print(c)

tensor([False, False, False])


In [80]:
print(b)
sorted_b, indices = torch.sort(b, dim=0, descending=False)
print(sorted_b)
print(indices)

tensor([9, 8, 7])
tensor([7, 8, 9])
tensor([2, 1, 0])


In [82]:
c = torch.clamp(a, min=0, max=2)
print(a)
print(c)

tensor([1, 2, 3])
tensor([1, 2, 2])


In [84]:
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x)
print(z)
z = torch.all(x)
print(z)

tensor(True)
tensor(False)


In [88]:
# indexing

batch_size = 10
features = 25
x = torch.rand(batch_size, features)

print(x[0].shape)
print(x[0,:])

torch.Size([25])
tensor([0.6110, 0.6717, 0.2135, 0.9642, 0.1474, 0.8865, 0.3119, 0.7986, 0.9963,
        0.3543, 0.3547, 0.4177, 0.2388, 0.0306, 0.7015, 0.3734, 0.8919, 0.8467,
        0.7987, 0.8303, 0.0645, 0.4145, 0.2775, 0.6057, 0.9131])


In [90]:
print(x[:,0])
print(x[:,0].shape)

tensor([0.6110, 0.3072, 0.0147, 0.7893, 0.2241, 0.3380, 0.4320, 0.1654, 0.6214,
        0.3933])
torch.Size([10])


In [92]:
print(x[2,0:10])

tensor([0.0147, 0.5716, 0.2059, 0.8876, 0.4700, 0.8069, 0.5599, 0.0614, 0.2733,
        0.9174])


In [93]:
x[0,0] = 100

In [94]:
x = torch.arange(10)
print(x)
indices = [2,5,8]
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [96]:
x = torch.rand(3,5)
r = torch.tensor([1,0])
c = torch.tensor([4,0])
print(x)
print(x[r,c])
print(x[r,c].shape)

tensor([[0.7653, 0.9565, 0.9580, 0.7850, 0.2878],
        [0.7848, 0.1543, 0.3807, 0.7582, 0.9891],
        [0.5193, 0.1172, 0.1165, 0.0130, 0.2235]])
tensor([0.9891, 0.7653])
torch.Size([2])


In [102]:
x = torch.arange(10)
print(x[(x<2) | (x>8)])
print(x[(x<2) & (x>8)])
print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [103]:
print(torch.where(x>5, x, x**2))

tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])


In [104]:
print(torch.tensor([0,0,1,2,3,4,5]).unique())

tensor([0, 1, 2, 3, 4, 5])


In [108]:
x = torch.rand(5,6,4)
print(x.ndimension())
print(x.numel())

3
120


In [109]:
# reshape

x = torch.arange(9)

x_3_3 = x.view(3,3)
print(x_3_3)
x_3_3 = x.reshape(3,3)
print(x_3_3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [111]:
y = x_3_3.t()
print(y)
print(y.view(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [112]:
print(y.reshape(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [115]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(x1)
print(x2)
print(torch.cat((x1,x2), dim=0))
print(torch.cat((x1,x2), dim=0).shape)

print(torch.cat((x1,x2), dim=1))
print(torch.cat((x1,x2), dim=1).shape)

tensor([[0.9768, 0.3728, 0.4420, 0.7005, 0.6968],
        [0.5216, 0.8484, 0.6567, 0.1194, 0.0951]])
tensor([[0.4742, 0.2730, 0.7670, 0.9696, 0.7315],
        [0.4094, 0.1482, 0.6894, 0.1865, 0.2258]])
tensor([[0.9768, 0.3728, 0.4420, 0.7005, 0.6968],
        [0.5216, 0.8484, 0.6567, 0.1194, 0.0951],
        [0.4742, 0.2730, 0.7670, 0.9696, 0.7315],
        [0.4094, 0.1482, 0.6894, 0.1865, 0.2258]])
torch.Size([4, 5])
tensor([[0.9768, 0.3728, 0.4420, 0.7005, 0.6968, 0.4742, 0.2730, 0.7670, 0.9696,
         0.7315],
        [0.5216, 0.8484, 0.6567, 0.1194, 0.0951, 0.4094, 0.1482, 0.6894, 0.1865,
         0.2258]])
torch.Size([2, 10])


In [116]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [117]:
batch = 64
x = torch.rand(batch, 2, 5)
z = x.view(batch, -1)
print(z.shape)

torch.Size([64, 10])


In [120]:
z = x.permute(0,2,1)
print(z.shape)

torch.Size([64, 5, 2])


In [123]:
x = torch.arange(10)
print(x.shape)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])


In [124]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

torch.Size([1, 1, 10])
