In [2]:
import torch
import numpy as np

In [3]:
t = torch.Tensor()
print(t)
print(type(t))

tensor([])
<class 'torch.Tensor'>


In [4]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [5]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [6]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.0, 2.0, 3.0])

In [7]:
print(t1.dtype)
print(t2.dtype)

torch.int64
torch.float32


In [8]:
t1+t2

tensor([2., 4., 6.])

In [9]:
t1.cuda()
t2.cuda()

tensor([1., 2., 3.], device='cuda:0')

In [10]:
t1+t2

tensor([2., 4., 6.])

In [11]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [12]:
torch.Tensor(data) # class constructor

tensor([1., 2., 3.])

In [13]:
torch.tensor(data) # factory function

tensor([1, 2, 3], dtype=torch.int32)

In [14]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [15]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
torch.rand(5,5)

tensor([[0.8563, 0.4355, 0.2452, 0.5011, 0.9517],
        [0.2563, 0.5281, 0.5177, 0.0152, 0.0437],
        [0.2772, 0.7704, 0.0637, 0.5154, 0.2673],
        [0.4764, 0.7169, 0.0783, 0.4487, 0.0296],
        [0.2017, 0.8021, 0.2509, 0.3307, 0.5341]])

In [20]:
data = np.array([1,2,3])

t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data) 
t4 = torch.from_numpy(data)

In [21]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [22]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [23]:
torch.get_default_dtype()

torch.float32

In [24]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
torch.tensor(np.array([1,2,3]), dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

# Memory Sharing

In [27]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [28]:
t1 = torch.Tensor(data) # pass by value
t2 = torch.tensor(data) # pass by value

t3 = torch.as_tensor(data) # pass by ref
t4 = torch.from_numpy(data) # pass by ref

In [29]:
data[0] = 0
data[1] = 0
data[2] = 0

In [30]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


In [32]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [33]:
t.size()

torch.Size([3, 4])

In [34]:
t.shape

torch.Size([3, 4])

In [35]:
len(t.shape)

2

In [36]:
torch.tensor(t.shape).prod()

tensor(12)

In [37]:
t.numel()

12

In [38]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [41]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [42]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [43]:
t.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [44]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [45]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

In [46]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [47]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [51]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=1))
print(t.reshape(1,12).squeeze().unsqueeze(dim=1).shape)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])
torch.Size([12, 1])


In [52]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [53]:
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [54]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [55]:
torch.cat((t1,t2), dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [56]:
torch.cat((t1,t2), dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])