In [68]:
import torch

In [69]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])
t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])
t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])


In [70]:
t = torch.stack((t1,t2,t3))
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

In [71]:
t.shape

torch.Size([3, 4, 4])

In [72]:
t = t.reshape(3,1,4,4)

In [73]:
t[0] # 1st image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [74]:
t[0][0] # 1st color channel of 1st image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [75]:
t[0][0][0] # 1st row of 1st channel of 1st image

tensor([1, 1, 1, 1])

In [76]:
t[0][0][0][0] # 1st pixel

tensor(1)

In [77]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [78]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [79]:
t.reshape(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [80]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [81]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [82]:
t.flatten(start_dim=1).shape # 1 is index for color channel

torch.Size([3, 16])

In [83]:
# Elementwise operation

In [84]:
import numpy as np

In [85]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t2 = torch.tensor([
    [9,8],
    [7,6]
])

In [86]:
t1[0]

tensor([1, 2])

In [87]:
t1[0][0]

tensor(1)

In [88]:
t2[0][0]

tensor(9)

In [89]:
# addtion
t1 + t2


tensor([[10, 10],
        [10, 10]])

In [90]:
t1 + 2

tensor([[3, 4],
        [5, 6]])

In [91]:
t1.add(2)

tensor([[3, 4],
        [5, 6]])

In [92]:
t1 -2

tensor([[-1,  0],
        [ 1,  2]])

In [93]:
t1.sub(2)

tensor([[-1,  0],
        [ 1,  2]])

In [94]:
t1 * 2

tensor([[2, 4],
        [6, 8]])

In [95]:
t1.mul(2)

tensor([[2, 4],
        [6, 8]])

In [96]:
t1 / 2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [97]:
t1.div(2)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])

In [98]:
# broadcasting

In [99]:
np.broadcast_to(2, t1.shape)

array([[2, 2],
       [2, 2]])

In [100]:
t1 + torch.tensor(np.broadcast_to(2, t1.shape))

tensor([[3, 4],
        [5, 6]])

In [101]:
t1 = torch.tensor([
    [1,1],
    [1,1]
])

In [102]:
t2 = torch.tensor([
    [2,4]
])

In [103]:
np.broadcast_to(t2, t1.shape)

array([[2, 4],
       [2, 4]], dtype=int64)

In [104]:
t1+t2

tensor([[3, 5],
        [3, 5]])

In [105]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [106]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [107]:
t == 0

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [108]:
t.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [109]:
t > 0

tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])

In [110]:
t.le(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [111]:
t < 0

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [112]:
t <= 0

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [113]:
t.le(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [114]:
t.abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [115]:
t.sqrt()

tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [116]:
t.neg()

tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [117]:
t.neg().abs()

tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [118]:
# Reduction operation

In [119]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)
t

tensor([[0., 1., 0.],
        [2., 0., 2.],
        [0., 3., 0.]])

In [120]:
t.sum()

tensor(8.)

In [121]:
t.numel()

9

In [122]:
t.sum().numel()

1

In [123]:
t.sum().numel() < t.numel()

True

In [124]:
t.prod()

tensor(0.)

In [125]:
t.mean()

tensor(0.8889)

In [126]:
t.std()

tensor(1.1667)

In [127]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
t

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [129]:
t.sum(dim=0) # arrays           

tensor([6., 6., 6., 6.])

In [130]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

In [131]:
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [132]:
t[0]

tensor([1., 1., 1., 1.])

In [133]:
t[1]

tensor([2., 2., 2., 2.])

In [134]:
t[2]

tensor([3., 3., 3., 3.])

In [135]:
t[0]+t[1]+t[2]

tensor([6., 6., 6., 6.])

In [136]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
])
t

tensor([[1, 0, 0, 2],
        [0, 3, 3, 0],
        [4, 0, 0, 5]])

In [137]:
t.max()

tensor(5)

In [138]:
t.argmax()

tensor(11)

In [139]:
t.flatten()

tensor([1, 0, 0, 2, 0, 3, 3, 0, 4, 0, 0, 5])

In [140]:
t.max(dim=0)

torch.return_types.max(
values=tensor([4, 3, 3, 5]),
indices=tensor([2, 1, 1, 2]))

In [141]:
t.max(dim=1)

torch.return_types.max(
values=tensor([2, 3, 5]),
indices=tensor([3, 1, 3]))

In [142]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [143]:
t.mean()

tensor(5.)

In [144]:
t.mean().item()

5.0

In [146]:
t.mean(dim=0).tolist()

[4.0, 5.0, 6.0]